= Git Homework Cheat Sheet
:numbered:

== What Am I Supposed to Do Again?

. Change into the directory with the homework repository (the *writer-workshop* directory).

. Open the *life_of_writer.adoc* file.

. Look up the section with your name.

. Write your section.

WARNING: In this excercise, only modify your section of the file. Do not change anything else in the other sections.

Do not forget to save the modified file.

== How Do I Commit?

. After saving the modified file, run the `git status` command from the command line. You will see the *life_of_writer.adoc* file printed in red.

. Run the `git add life_of_writer.adoc` command to stage the changes.

. Run the `git commit` command to make a commit.

. In the editor that opens:

.. Press `i` to enter Insert mode.

.. Write the commit message on the first line of the editor.

.. Press `Esc` to exit Insert mode.

.. Write `:write` to save the commit message.

.. Write `:quit` to exit the editor.

. Run the `git log` command to make sure the commit is saved in the project history.

After this, the commit is ready in your local repository. The next step is uploading it to the remote repository.

== Uploading to a Remote Repository

If you have a commit ready in your local repository, run the `git push` command to upload it to the remote repository. For example:

-------------------------------------------------------------------------------------------
[writer@writer git-episodes]$ git push

Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 651 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
	To git@gitlab.cee.redhat.com:ccs-internal-docs/git-episodes.git
	   6b39121..2e9da3e  master -> master
-------------------------------------------------------------------------------------------

After this, your committed work is added to the remote repository. Your homework is done!

== What to Do When a Commit Was Rejected?

Whenever you push a commit, Git checks if the remote repo matches your local repo. If they do not match, it means that another writer had pushed their changes before you.

In such situations, Git does not allow you to push your commit, and prints the following error message:

-------------------------------------------------------------------------------------------
To git+ssh://code.engineering.redhat.com/git-episodes.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git+ssh://code.engineering.redhat.com/git-episodes.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
-------------------------------------------------------------------------------------------

This message means that Git is asking you to pull the other contributor's work: to download it from the shared repo and apply it. After that, you will be allowed to push again. To do this:

. Download the other writer's revision by running the `git pull --rebase` command:
+
---------------------------------------------------------
[writer@writer git-episodes]@ git pull --rebase
remote: Counting objects: 45, done
remote: Finding sources: 100% (26/26)
remote: Total 26 (delta 15), reused 26 (delta 15)
Unpacking objects: 100% (26/26), done.
From git+ssh://code.engineering.redhat.com/git-episodes
   4802de0..ccfd4d3  master     -> origin/master
First, rewinding head to replay your work on top of it...
Applying: fixed some typos
---------------------------------------------------------
+
. Upload the commit by running the `git push` command:
+
-------------------------------------------------------------------------------------------
[writer@writer git-episodes]$ git push

Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 651 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
	To git@gitlab.cee.redhat.com:ccs-internal-docs/git-episodes.git
	   6b39121..2e9da3e  master -> master
-------------------------------------------------------------------------------------------

After this, your homework is finally done.
